Dev
mate-academy/py-copy-file pull request #1055
Opened 2024-07-06 11:19 UTC by VasylRysan

2024-07-06 14:32 UTC, vsmutok requested changes

2024-07-06 14:32 UTC, vsmutok commented on app/main.py
> +        return
how will the user understand that something went wrong? 
give an informative message

2024-07-06 14:32 UTC, vsmutok commented on app/main.py
> +        return
the same

2024-07-06 14:32 UTC, vsmutok commented on app/main.py
> +    operation, current_file, new_file = command.split()
`split()` - don't use it twice, use it only once

2024-07-07 10:57 UTC, vasylhnatiuk approved these changes

2025-04-02 06:14 UTC, closed without merging