Task
mate-academy/py-copy-file pull request #1108
Opened 2024-08-06 13:53 UTC by Poznanskyi

2024-08-07 05:49 UTC, Oleksl888 requested changes

2024-08-07 05:49 UTC, Oleksl888 commented on app/main.py
> +    command, first_name, second_name = command.split()
what if command is wrong and doesn't have exactly three elements?

2024-08-07 05:49 UTC, Oleksl888 commented on app/main.py
> +        with (open(first_name, "r") as file_in,
would be nice to wrap it in try-except to catch file-related errors

2024-08-08 05:07 UTC, Oleksl888 requested changes

2024-08-08 05:07 UTC, Oleksl888 commented on app/main.py
> +    command, first_name, second_name = command.split()
you need to check if split-command has exactly three elements otherwise your program will crash during unpacking

2024-08-08 05:07 UTC, Oleksl888 commented on app/main.py
> +    command, first_name, second_name = command.split()
I'd suggest to apply `try` block only to file-related operations - starting from when you open file.

2024-08-08 05:07 UTC, Oleksl888 commented on app/main.py
> +    except FileNotFoundError:
OSError would cover more file and system related errors

2024-08-13 12:19 UTC, LiudmylaKulinchenko requested changes
`you need to check if split-command has exactly three elements otherwise your program will crash during unpacking` -- you didn't fix this comment

2024-08-13 13:01 UTC, LiudmylaKulinchenko approved these changes
Good job 🌷

2025-09-10 11:56 UTC, closed without merging