solution
mate-academy/py-copy-file pull request #351
Opened 2023-02-22 11:14 UTC by T-Vlad-96

2023-02-22 11:23 UTC, olena-hul requested changes

2023-02-22 11:23 UTC, olena-hul commented on app/main.py
> +    new_file = command_and_file_names.split()[2]
Use variable to store command_and_file_names.split() result. Validate input command, whether it is cp or not and check command lenght (should be exacty 3 arguments)

2023-02-25 12:16 UTC, ArsenPidhoretskyi approved these changes
Good job!

2023-02-25 12:16 UTC, ArsenPidhoretskyi commented on app/main.py
> +        new_file = command_and_file_names[2]
use correct name: destination_file_path

2025-11-02 16:55 UTC, closed without merging