Solution_
mate-academy/py-copy-file pull request #360
Opened 2023-03-04 13:47 UTC by khachatrian2000

2023-03-04 14:00 UTC, ArsenPidhoretskyi requested changes

2023-03-04 14:00 UTC, ArsenPidhoretskyi commented on app/main.py
> +    cp, file_1, file_2 = command.split()
Rename variables also:
cp -> input_command
file_1 -> source_file_path
file_2 -> destination_file_path

2023-03-05 11:02 UTC, katevasilenko reviewed
Looks good to me

2023-03-05 11:09 UTC, khachatrian2000 commented
> Looks good to me

cool! could you please approve the request then?

2023-03-05 11:56 UTC, vasylhnatiuk approved these changes
Good job!

2026-03-19 15:50 UTC, closed without merging