Solution
mate-academy/py-copy-file pull request #384
Opened 2023-04-05 14:53 UTC by goldenuni

2023-04-05 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +            f_out.write(line)
u can write whole file, it's not necessary to write it line by line

2023-04-05 16:38 UTC, Bohdan-Salamakha commented on app/main.py
> +        raise ValueError("Incorrect FileIn and FileOut.")
u don't need to do anything if files are the same
https://github.com/mate-academy/py-copy-file#:~:text=It%20must%20do%20nothing%20in%20case%20the%20user%20is%20trying%20to%20copy%20file%20to%20file%20with%20the%20same%20name.

2023-04-05 16:39 UTC, Bohdan-Salamakha commented on app/main.py
> +    cp, file_in, file_out = command.split()
don't call commad.split() twice
create a separated variable for it and call on demand

2023-04-05 16:39 UTC, Bohdan-Salamakha requested changes
v1

2023-04-06 08:36 UTC, olena-hul requested changes

2023-04-06 08:36 UTC, olena-hul commented on app/main.py
> +    cp, file_in, file_out = command_sep[0], command_sep[1], command_sep[2]
```suggestion
    cp, file_in, file_out = command_sep
```

2023-04-06 09:26 UTC, Bohdan-Salamakha approved these changes

2024-03-22 10:29 UTC, closed without merging