Solution
mate-academy/py-copy-file pull request #526
Opened 2023-08-09 15:57 UTC by AndriiIshchenko

2023-08-09 18:22 UTC, vsmutok requested changes

2023-08-09 18:22 UTC, vsmutok commented on app/main.py
> +    command_in_list = command.split(" ")
```suggestion
    command_in_list = command.split()
```

2023-08-09 18:22 UTC, vsmutok commented on app/main.py
> +    if command_in_list[0] == "cp" and command_in_list[1] != command_in_list[2]:
check if command_in_list has 3 elements before it

2023-08-09 18:57 UTC, vsmutok requested changes

2023-08-09 18:57 UTC, vsmutok commented on app/main.py
> +    if (len(command_in_list) == 3
```suggestion
    if (len(command.split()) == 3:
            command_name, filename, copy_filename = command.split()
```

2023-08-09 18:57 UTC, vsmutok commented on app/main.py
> +    if (len(command_in_list) == 3
it looks better

2023-08-10 08:53 UTC, ArsenPidhoretskyi approved these changes
Well done!

2026-08-22 12:49 UTC, closed without merging