Solution
mate-academy/py-copy-file pull request #654
Opened 2023-10-24 13:20 UTC by maksimpro001

2023-10-24 13:27 UTC, NikOneZ1 requested changes
The solution won't work because at the moment it will only copy files with the same name, and should only copy files with different names, as the task description says. Fix that, please

2023-10-24 14:59 UTC, NikOneZ1 requested changes

2023-10-24 14:59 UTC, NikOneZ1 commented on app/main.py
> +        return
You able to merge this two conditions
```suggestion
    if text[0] != "cp" or text[1] == text[2]:
        return
```

2023-10-24 14:59 UTC, NikOneZ1 commented on app/main.py
> +        f2.write(f1.read())
Use more convenient naming 
```suggestion
    with open(text[1], "r") as file1, open(text[2], "w") as file2:
        file2.write(file1.read())
```

2023-10-25 08:24 UTC, EdAlekseiev requested changes

2023-10-25 08:24 UTC, EdAlekseiev commented on app/main.py
> +    text = command.split(" ")
`" "` is default value for `split`

2023-10-25 08:24 UTC, EdAlekseiev commented on app/main.py
> +    text = command.split(" ")
```suggestion
    text = command.split()
```

2023-10-25 13:43 UTC, NikOneZ1 approved these changes
Well done!

2024-01-08 08:58 UTC, closed without merging