Develop
mate-academy/py-copy-file pull request #756
Opened 2024-01-18 02:44 UTC by PyCore23

2024-01-18 09:32 UTC, vasylhnatiuk requested changes

2024-01-18 09:32 UTC, vasylhnatiuk commented on app/main.py
> +    ref = command.split(" ")[1]
what is ref? what if command does not have 3 arguments?

2024-01-18 09:32 UTC, vasylhnatiuk commented on app/main.py
> +    new = command.split(" ")[2]
use only one time split(), don't repeat yourself

2024-04-16 19:22 UTC, EdAlekseiev requested changes

2024-04-16 19:22 UTC, EdAlekseiev commented on app/main.py
> +    parts = command.split(" ")
`" "` is default value for `split`.
```suggestion
    parts = command.split()
```

2024-04-16 19:22 UTC, EdAlekseiev commented on app/main.py
> +    if len(parts) < 3:
Also, check that command start with `cp`

2024-04-24 05:20 UTC, vsmutok requested changes

2024-04-24 05:20 UTC, vsmutok commented on app/main.py
> +    parts = command.split(" ")
```suggestion
    parts = command.split()
```

2024-04-24 05:20 UTC, vsmutok commented on app/main.py
> +    parts = command.split(" ")
`" "` is default value for `split()`

2024-04-24 05:20 UTC, vsmutok commented on app/main.py
> +    if len(parts) < 3:
Also, check that command start with `cp`

2024-04-24 05:20 UTC, vsmutok commented on app/main.py
> +        new = parts[2]
```suggestion
        _, source, new = parts
```

2024-05-03 05:46 UTC, vsmutok requested changes

2024-05-03 05:46 UTC, vsmutok commented on app/main.py
> +    parts = command.split(" ")
`" "` is default value for `split()`

2024-05-03 05:46 UTC, vsmutok commented on app/main.py
> +            with open(parts[2], "w") as destination_file:
use one `with`

```python
with open(.., "r") as f, open(..., "w") as f2:
```

2024-05-17 10:00 UTC, closed without merging