Solution
mate-academy/py-copy-file pull request #798
Opened 2024-01-31 16:26 UTC by mykyta-so

2024-01-31 17:11 UTC, vsmutok requested changes

2024-01-31 19:53 UTC, vsmutok requested changes

2024-01-31 19:53 UTC, vsmutok commented on app/main.py
> +    cp_command, source_name, destination_name = command.split()
before unpacking, you should check that the length of `command.split()` is three

2024-01-31 19:53 UTC, vsmutok commented on app/main.py
> +        print("1")
why???

2024-01-31 19:55 UTC, mykyta-so commented on app/main.py
> +        print("1")
sorry, I forgot to delete it

2024-02-01 18:24 UTC, ArsenPidhoretskyi requested changes

2024-02-02 09:29 UTC, ArsenPidhoretskyi approved these changes
Well done!

2025-07-23 17:33 UTC, closed without merging