'Solution'
mate-academy/py-copy-file pull request #98
Opened 2022-08-25 10:34 UTC by Diliaver

2022-08-25 13:46 UTC, Abnormaltype requested changes

2022-08-25 13:46 UTC, Abnormaltype commented on app/main.py
> +        pass
remove unnecessary else

2022-08-25 13:46 UTC, Abnormaltype commented on app/main.py
> +    if list[1] != list[2]:
you should check the input command

2022-08-25 13:46 UTC, Abnormaltype commented on app/main.py
> +                open(f"{list[2]}", "a") as secondfile:
firstfile, secondfile - write more correct names for these variables

2022-08-29 10:19 UTC, IvanRamyk approved these changes

2024-07-25 13:24 UTC, closed without merging